apiVersion: v1
kind: Pod
metadata:
  name: prod-app
  labels:
    app: prod-app
spec:
  containers:
  - name: app-container
    image: quay.io/rhacs-demo/sample-image:getting-started-old
    ports:
    - containerPort: 8080
    securityContext:
privileged: true
