apiVersion: v1
kind: Pod
metadata:
  namespace: meetip
  name: prod-app
  labels:
    app: prod-app
spec:
  #serviceAccountName: visa-processor
  automountServiceAccountToken: false
  containers:
  - name: app-container
    image: quay.io/ralvares/ubi8:minimal
    ports:
    - containerPort: 8080
    securityContext:
      privileged: false
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
